[info]
language = "sv"

[texts]
back_dock_failed = "Kunde ej nå laddstationen, tabort hinder och gör rent laddstationens signalfyrar."
bin_in = "Dammsamlare installerad."
binout_error10 = "Dammfilter skitigt.  Tabort dammsamlaren och gör rent filtret!"
bin_out = "Dammsamlare borttagen."
bl_recovery_bootfailed = "Gick ej att starta. Återställer till fabriksinställningar. Detta kommer ta ungefär 5 minuter."
bl_recovery_bootfailure = "Gick ej att att boota.  Vänligen kontakta oss för support."
bl_recovery_failed = "Kunde ej återställa fabriksinställningar. Testa igen."
bl_recovery_retry = "Återställer till fabriksinställningar.  Detta kommer ta ungefär 5 minuter."
bl_recovery_start = "Återställer till fabriksinställningar.  Detta kommer ta ungefär 5 minuter."
bl_recovery_updatefailed = "Gick ej att uppdatera mjukvaran.  Återställer till fabriksinställningar.  Detta kommer ta ungefär 5 minuter."
charging = "Laddar."
clean_bin = "Töm dammsamlaren."
clean_finish = "Städning slutförd. Återgår till dockan."
clean_finish_remind_clean_waterbox = "Städning slutförd och laddning startad. Det är rekommenderat att tabort och göra rent moppen."
clean_water_box = "Var vänlig gör ren moppen då och då."
di = "Ding dong!"
ding = "Ding!"
error1 = "Fel 1, Vrid laserenheten och undersök att den ej fastnat eller är blockerad."
error2 = "Fel 2, Rengör och rör försiktigt stötfångaren."
error3 = "Fel 3, Flytta roboten till en ny position och starta igen."
error4 = "Fel 4, Rengör klippsensorn. Flytta roboten till bort från kanten och starta igen."
error5 = "Fel 5, Tabort och rengör huvudborsten."
error6 = "Fel 6, Tabort och rengör  sidoborsten."
error7 = "Fel 7, Undersök om hjul kan ha fastnat. Flytta roboten till en ny position och starta igen."
error8 = "Fel 8, Flytta eventuella hinder runt roboten."
error9 = "Fel 9, Återinstallera dammsamlaren och filter."
error10 = "Fel 10, Undersök filtret. Om vått, använd ett tort. Om tort, rengör och försök igen."
error11 = "Fel 11, Starkt magnetfält detekterat. Flytta roboten bort från gränstejpen och starta igen."
error12 = "Fel 12, Batterinivå för låg, låt ladda före användning."
error13 = "Fel 13, Laddningsfel. Rengör laddkontakter och testa igen."
error14 = "Fel 14, Batterifel."
error15 = "Fel 15, Rengör väggsensor."
error16 = "Fel 16, Placera och starta roboten på ett plant underlag."
error17 = "Fel 17, Sidborte modulfel, testa att starta om enheten."
error18 = "Fel 18, Sugfläkts-fel, testa att starta om enheten."
error19 = "Fel 19, Laddstationen saknar nätanslutning. Undersök strömförsörjningen."
error21 = "Fel 21, Höjdsensor har utlöst. Flytta roboten och starta igen."
error22 = "Fel 22, Rengör laddsensor på roboten."
error23 = "Fel 23, Rengör signalfyrar på laddstationen"
error24 = "Fel 24, Förbjudet område eller barriärtejp detekterat, flytta roboten till ett tillåtet område och starta igen."
error25 = "Fel 25, Rengör kamerasensor."
error26 = "Fel 26, Rengör väggsensor."
error_internal = "Ett internt fel inträffade. Starta om roboten."
findme = "Hej! Här är jag!"
finish = "Städning slutförd."
goto_complete = "Mål nått."
goto_failed = "Kunde ej nå målet."
goto = "Kör mot målet."
home = "Kör tillbaka till laddstationen."
map_restore = "Kartan har återställts, laddning startad."
no_power_charging = "Batterinivå låg. Behöver ladda mer."
no_power = "Låg batterinivå, kör tillbaka till laddstationen."
no_spot_on_dock = "Flytta roboten till valt område, sedan starta punktrengöring."
pause = "Pausat."
positioning = "Positionerar, Vänligen vänta."
positioning_map_changed = "Karta bytt, börjar att städa."
positioning_still = "Återetablerar position."
positioning_success = "Position etablerad."
power_off = "Stänger av."
power_off_rejected = "Tabort roboten från laddstationen och stäng av."
power_resume_clean = "Batteri laddat, återgår till att städa."
relocate_failed = "Ruttplanering fallerade, kunde ej nå målet."
remote_complete = "Fjärrstyrning avbruten."
remote = "Startar fjärrstyrning."
restart_clean_fromdock = "Positioneringsfel, startar ny fullständig städning."
restart_clean_nodock = "Positioneringsfel, ogiltig karta. Startar ny städning."
restart_clean = "Positioneringsfel, startar ny städning."
resume_backtodock = "Positioneringsfel, ogiltig karta. Fortsätter tillbaka mot laddstationen."
resume_clean = "Återgår till städning."
resume_home = "Fortsätter tillbaka mot laddstationen."
resume_room = "Återgår till rumstädning."
resume_spot = "Positioneringsfel, ogiltig karta. Återgår till punktstädning."
resume_zone = "Återgår områdesstädning."
return_no = "Kan ej återgå till startposition."
return_yes = "Kan ej hitta laddstationen. Flytta roboten närmare laddstationen och testa igen."
room_complete = "Rumstädning slutförd, återgår till laddstation."
room_failed = "Rumstädning ej slutförd, kunde ej nå specificerat rum, återgår till laddstation."
room = "Startar rumstädning."
room_partialdone = "Rumstädning slutförd, återgår till laddstation. Vissa områden kunde ej nås."
room_water_box_in = "Startar rumstädning. Vänligen fyll vattentank."
saving_map = "Sparar karta, vänligen vänta."
spot = "Startar punktrengöring."
start = "Börjar städa."
start_water_box_in = "Börjar städa.  Vänligen fyll vattentank."
stop_clean = "Avryter städning."
stop_goto = "Avryter färd till mål."
stop_room = "Avryter vald rumstädning."
stop_scheduled_clean = "Positioneringsfel. Schemalagd städning avbruten."
stop_spot = "Avbröt punktrengöring."
stop_zone = "Avbröt valt områdesrengöring."
sysupd_complete = "Uppdatering slutförd."
sysupd_failed = "Uppdatering misslyckades. Återgår till föregående version."
sysupd_notready = "Batteriet måste laddas till minst tjugo procent före mjukvaruuppdatering."
sysupd_start = "Uppdaterar mjukvara. Detta kan ta mellan 5 till 10 minuter."
sysupd_wip = "Uppdaterar.  Vänligen vänta."
timed_clean = "Startar schemalagt städning."
water_box_carriage_in = "Moppläge redo. Se till att moppduk är installerad."
water_box_carriage_out = "Moppinfästning borttagen. Byter till dammsugarläger."
water_box_in = "Vattentank installerad."
water_box_out = "Vattentank borttagen."
wifi_reset = "Återställer Wi-Fi."
wifi_ssid_wrong = "Wi-Fi-anslutning misslyckades, anslut till ditt WiFi."
wifi_connect_failed = "Wi-Fi-anslutning misslyckades, kontrollera lösenord och testa igen."
wifi_connect_start = "Etablerar Wi-Fi-anslutning"
wifi_connected = "Wi-Fi-anslutning etablerad"
zone_complete = "Områdesstädning slutförd. Återgår mot laddstationen."
zone_failed = "Områdesstädning ofullständig.  Kunde ej nå specificerat område. Återgår mot laddstationen."
zone = "Startar områdesstädning."
zone_partialdone = "Områdesstädning slutförd. Återgår mot laddstationen. Vissa områden kunde ej nås."
zone_water_box_in = "Startar områdesstädning."
start_greeting = "Gott nytt år till dig, Hundens lyckliga år."
tmod_start_upload_log = "Börja ladda upp loggar."
