[info]
language = "en"

[texts]
back_dock_failed = "Couldn't reach the charging dock, remove any obstacles, and clean the dock's transmission area."
bin_in = "Dustbin installed."
binout_error10 = "Filter is clogged.  Remove the dustbin, and clean the filter!"
bin_out = "Dustbin removed."
bl_recovery_bootfailed = "Failed to start.  Restoring factory settings.  This will take about 5 minutes."
bl_recovery_bootfailure = "Failed to boot.  Please contact us for after sales consultation."
bl_recovery_failed = "Failed to restore factory settings.  Try again."
bl_recovery_retry = "Restoring factory settings.  This will take about 5 minutes."
bl_recovery_start = "Restoring factory settings.  This will take about 5 minutes."
bl_recovery_updatefailed = "Failed to update.  Restoring factory settings.  This will take about 5 minutes."
charging = "Charging."
clean_bin = "Empty the dustbin."
clean_finish = "Finished cleaning. Going back to the dock."
clean_finish_remind_clean_waterbox = "Cleaning completed and recharging started.  It is recommended to remove the mopping cloth tray and clean the cloth."
clean_water_box = "Please clean the mop in a timely manner."
di = "Ding dong!"
ding = "Ding!"
error1 = "Error 1, Turn the laser unit, and check that it is not jammed, or blocked."
error2 = "Error 2, Clean and lightly tap the bumper."
error3 = "Error 3, Move the main unit to a new location, and restart."
error4 = "Error 4, Clean cliff sensors. Move the main unit away from any drops, then restart."
error5 = "Error 5, Remove and clean the main brush and brush bearing."
error6 = "Error 6, Remove and clean the side brush."
error7 = "Error 7, Check that wheels are not blocked, then move the main unit to a new location, and restart."
error8 = "Error 8, Remove any obstacles around the main unit."
error9 = "Error 9, Reinstall dustbin and filter."
error10 = "Error 10, Check the filter.  If wet, use a dry one.  If dry, clean it, and try again."
error11 = "Error 11, Strong magnetic field detected. Move the device away from barrier tape and restart."
error12 = "Error 12, Battery level too low, recharge before use."
error13 = "Error 13, Charging error.  Clean charging contacts, and try again."
error14 = "Error 14, Battery error."
error15 = "Error 15, Clean wall sensor."
error16 = "Error 16, Place and start the main unit on a level floor."
error17 = "Error 17, Side brush module error. Reset the main unit."
error18 = "Error 18, Fan error. Reset the main unit."
error19 = "Error 19, There is no current on the charging base. Check connection to a power supply."
error21 = "Error 21, Height sensor has been pressed.  Move the main unit, and restart."
error22 = "Error 22, Clean the recharge sensor on the main unit."
error23 = "Error 23, Clean the transmission area on the charging dock."
error24 = "Error 24, No-Go-Zone or barrier tape detected. Move the main unit away, and restart."
error25 = "Error 25, Clean the vision sensor."
error26 = "Error 26, Clean wall sensor."
error_internal = "An internal error occurred. Reboot the system."
findme = "Hi! I'm over here!"
finish = "Cleaning completed."
goto_complete = "Reached the target."
goto_failed = "Could not reach the target."
goto = "Going to the target."
home = "Going back to the dock."
map_restore = "Map has been restored, starting to charge."
no_power_charging = "Low battery. More charging needed."
no_power = "Low battery, going back to the dock."
no_spot_on_dock = "Move the main unit to the target area, then start spot cleaning."
pause = "Paused."
positioning = "Positioning, please wait."
power_off = "Turning off."
power_off_rejected = "Take the main unit off the charging dock to turn off."
power_resume_clean = "Battery charged, resuming cleaning."
relocate_failed = "Route planning failed, could not reach the target."
remote_complete = "Remote control stopped."
remote = "Starting remote control."
restart_clean_fromdock = "Positioning failure, starting a new clean to rebuild the map."
restart_clean_nodock = "Positioning failure, invalid map. Starting a new clean."
restart_clean = "Positioning failure, starting a new clean."
resume_backtodock = "Positioning failure, invalid map. Continue returning to the dock."
resume_clean = "Resuming cleaning."
resume_home = "Continue returning to the dock."
resume_room = "Resuming room cleaning."
resume_spot = "Positioning failure, invalid map. Continuing spot cleaning."
resume_zone = "Resuming zoned cleaning."
return_no = "Couldn't return to the starting point."
return_yes = "Couldn't find the dock. Bring main unit closer to the dock, and retry."
room_complete = "Room cleaning complete, going back to the dock."
room_failed = "Room cleaning incomplete, could not reach a specified room, going back to the dock."
room = "Starting room cleaning."
room_partialdone = "Room cleaning complete, going back to the dock. Some areas could not be reached."
room_water_box_in = "Starting room cleaning.  Ensure water tank is properly filled."
saving_map = "Saving map, please wait."
spot = "Starting spot cleaning."
start = "Starting to clean."
start_water_box_in = "Starting to clean.  Ensure water tank is properly filled."
stop_clean = "Stop cleaning."
stop_goto = "Stopping travel to target."
stop_room = "Stop targeted room cleaning."
stop_scheduled_clean = "Positioning failed. Scheduled cleaning cancelled."
stop_spot = "Stopped spot cleaning."
stop_zone = "Stopped targeted area cleaning."
sysupd_complete = "Update complete."
sysupd_failed = "Couldn't update firmware. Returning to previous version."
sysupd_notready = "Recharge to at least twenty percent before updating."
sysupd_start = "Updating firmware. This may take 5 to 10 minutes."
sysupd_wip = "Updating.  Please wait."
timed_clean = "Starting scheduled cleaning."
water_box_carriage_in = "Mop mode ready.  Ensure mopping cloth is installed."
water_box_carriage_out = "Mop bracket removed.  Switching to vacuum mode."
water_box_in = "Water tank installed."
water_box_out = "Water tank removed."
wifi_reset = "Resetting Wi-Fi."
zone_complete = "Zoned cleaning completed. Going back to the dock."
zone_failed = "Zoned cleaning incomplete.  Could not reach a specified zone. Going back to the dock."
zone = "Starting zoned cleanup."
zone_partialdone = "Zone cleaning completed. Going back to the dock. Some zones could not be reached."
zone_water_box_in = "Starting zoned cleaning."